<a href="https://colab.research.google.com/github/uk-zash/Deep-Learning/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as numpy
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


# Creating Tensors

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [6]:
torch.tensor([1 , 2, 3])

tensor([1, 2, 3])

In [8]:
vector = torch.tensor([1,2,4])
print(vector.ndim)

1


In [9]:
vector.shape

torch.Size([3])

In [10]:
matrix = torch.tensor([[1,2,3] ,
                       [3,2,1]])
print(matrix.ndim)

2


In [11]:
matrix.shape

torch.Size([2, 3])

In [12]:
tensor = torch.tensor([[[1 , 2] ,
                        [1 , 2],
                        [1 , 3]]])

print(tensor.ndim)

3


In [13]:
tensor.shape

torch.Size([1, 3, 2])

# Random Tensors

Random tensors are importand because the way many neural networks learn is that they start with tenosrs full of random numbers then adjust those ranodm numbers to better represent the data

In [19]:
random_tensor = torch.rand(2 , 3 ,4)
random_tensor

tensor([[[0.3546, 0.0657, 0.4380, 0.7216],
         [0.1881, 0.6200, 0.8642, 0.3636],
         [0.5501, 0.3928, 0.3791, 0.7502]],

        [[0.0065, 0.4531, 0.6025, 0.3278],
         [0.3607, 0.0026, 0.6908, 0.6432],
         [0.0439, 0.0319, 0.8381, 0.7591]]])

In [18]:
random_tensor.shape

torch.Size([1, 3, 4])

For Image

In [21]:
random_image = torch.rand(size = (224 , 224 , 3))

random_image.shape , random_image.ndim

(torch.Size([224, 224, 3]), 3)

# Range


In [25]:
one_to_ten = torch.arange(0 , 10)

In [26]:
torch.zeros_like(input = one_to_ten)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Data Type

In [33]:
float_32 = torch.tensor([2 , 6 , 9] , dtype =torch.float16,
                        device = "cuda",
                        requires_grad = False)
float_32

tensor([2., 6., 9.], device='cuda:0', dtype=torch.float16)

In [34]:
float_32.device

device(type='cuda', index=0)

In [38]:
A = torch.tensor([[1 , 2 , 4],
                  [1 , 2 , 4]])

B = torch.tensor([[1 , 2, 4],
                  [1 , 2 ,4 ]])

torch.matmul(A , B.T)

tensor([[21, 21],
        [21, 21]])

In [40]:
x = torch.tensor([1 , 4 ,23 , 41])

torch.min(x) , torch.max(x)

(tensor(1), tensor(41))

In [42]:
torch.mean(x.type(torch.float32))

tensor(17.2500)

In [43]:
x.argmin()

tensor(0)

In [45]:
x.argmax()

tensor(3)

* Reshaping - reshapes an input tensors to a define Shape
* View - Return a view of an input tenosr of certain shape but keep the same memory as the original
* Stacking - Combine multiple tensors on top of each other
* Squeeze - remove all 1 dimension from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - Return a view of the input with dimension permuted in a certain way

In [60]:
y = torch.arange(1. , 11.)
y

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [61]:
y_reshape = y.reshape(5 , 2)

In [62]:
y_reshape

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [66]:
x_stacked = torch.stack([y , y , y ,y] , dim = 0)
x_stacked

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [67]:
squeeze = torch.squeeze(y)

In [73]:
squeeze.shape

torch.Size([10])

In [72]:
torch.unsqueeze(y , dim = 0)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [74]:
!nvidia-smi

Sun Sep  8 18:33:38 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   78C    P0              33W /  70W |    121MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [75]:
torch.cuda.is_available()

True

# Setup


In [77]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

#Count devices

In [78]:
torch.cuda.device_count()

1

In [79]:
tenosr_on_gpu = y.to(device)
tenosr_on_gpu

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], device='cuda:0')

In [82]:
tenosr_on_gpu.cpu().numpy()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)